### ISSUE TITLE
Different error messages

### ISSUE THREAD

**Issue by Joshcookfair** [dimxasnewfrozen/submission-app#12]
When I put an an invalid email, i get this:
![screenshot 2017-03-15 17 03 20](https://cloud.githubusercontent.com/assets/5664247/23970754/638654c4-09a1-11e7-850c-75f87cdc341c.png)

When i leave empty field thats required, i get this:
![screenshot 2017-03-15 17 03 49](https://cloud.githubusercontent.com/assets/5664247/23970764/6b98875e-09a1-11e7-92fe-5304794be6ba.png)

Can we make it look more like the first error, but make it red?

**Comment by dimxasnewfrozen** [comment]
Cleaned up.
