### ISSUE TITLE
I can submit an image thumbnail URl that is not actually a link

### ISSUE THREAD

**Issue by Joshcookfair** [dimxasnewfrozen/submission-app#13]
it allows me to submit plain text, doesnt check that its an actual link. 

Same happens with teammate's email, i can submit "lksjdalksdj" and it accepts that.

![screenshot 2017-03-15 17 05 36](https://cloud.githubusercontent.com/assets/5664247/23970811/a043d382-09a1-11e7-9906-115754346fbf.png)

**Comment by dimxasnewfrozen** [comment]
donzo!
