### ISSUE TITLE
URL validation

### ISSUE THREAD

**Issue by yuliyapeshkova** [dimxasnewfrozen/submission-app#19]
Maybe need to add validation logic for image URLs?
Was able to submit with this in the form-field

![screenshot 2017-03-15 17 25 22](https://cloud.githubusercontent.com/assets/15108568/23971478/82115a1c-09a4-11e7-9935-504508f6e009.png)

* Why did you decide to use URLs instead of image upload function?

**Comment by dimxasnewfrozen** [comment]
donzo!
